server:
  port: 8100
eureka:
  instance:
    appname: gateway
  client:
    service-url:
      defaultZone: http://admin:admin@eureka10086.com:10086/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: consume-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/provider/**
            - After=2020-01-01T00:00:00.000+08:00[Asia/Shanghai]
            - Before=2030-01-01T00:00:00.000+08:00[Asia/Shanghai]
    sentinel:
      log:
        dir: D:\logs\sentinel\ # 日志存储位置
      transport:
        dashboard: 172.27.23.85:8199
        heartbeatIntervalMs: 5000
      eager: true
