server:
  port: 8100
eureka:
  instance:
    appname: gateway
  client:
    service-url:
      defaultZone: http://admin:admin@eureka10086.com:10086/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: consume-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/provider/**
            - After=2020-01-01T00:00:00.000+08:00[Asia/Shanghai]
            - Before=2030-01-01T00:00:00.000+08:00[Asia/Shanghai]
  main:
    allow-bean-definition-overriding: true
csp:
  sentinel:
    eager: true
    log:
      dir: D:\logs\sentinel\
    transport:
      dashboard: 172.27.23.85:8199
      heartbeat-interval-ms: 3000
apollo:
  meta-server-address: http://172.27.23.85:8080
  app-id: gateway
  cache-dir: D:\Logs\apollo\cache\
  env: dev
  cluster: default
  access-token: ff5ca79fef9b8052e416d580bd608bf60223c1c00bc977dac93699102767dd34
