dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: 28080

  registry:
    address: zookeeper://172.27.23.85:2181
  metadata-report:
    address: zookeeper://172.27.23.85:2181




server:
  port: 8081