dubbo:
  application:
    name: provider
  #    enable-empty-protection: false
  protocol:
    name: dubbo
    port: 28080
  config-center:
    address: zookeeper://172.27.23.85:2181?username=admin&password=admin
    username: admin
    password: admin
  registry:
    address: zookeeper://172.27.23.85:2181?username=admin&password=admin
    username: admin
    password: admin
  metadata-report:
    address: zookeeper://172.27.23.85:2181?username=admin&password=admin
    username: admin
    password: admin

server:
  port: 8081