server:
  port: 10086
spring:
  application:
    name: eureka-server1
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    #注册中心实例的主机名
    hostname: eureka10086.com
  client:
    #  是否注册到eureka,false表示不向注册中心注册自己。
    register-with-eureka: false
    #  是否从eureka获取注册信息,false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@eureka10086.com:10086/eureka/,http://admin:admin@eureka10087.com:10087/eureka
  server:
    # 最低接受心跳比
    renewal-percent-threshold: 0.49