dubbo:
  application:
    name: provider
  #    enable-empty-protection: false
  protocol:
    name: dubbo
    port: 28080
  config-center:
    address: zookeeper://172.27.23.85:2181
  registry:
    address: zookeeper://172.27.23.85:2181
  #    enable-empty-protection: false
  metadata-report:
    address: zookeeper://172.27.23.85:2181

server:
  port: 8081