server:
  port: 8086
eureka:
  instance:
    appname: consumer-service
  client:
    service-url:
      #      defaultZone: http://admin:admin@eureka10086.com:10086/eureka/,http://admin:admin@eureka10087.com:10087/eureka
      defaultZone: http://admin:admin@eureka10086.com:10086/eureka/
    registry-fetch-interval-seconds: 3
spring:
  application:
    name: consumer-service



